In [411]:
from bs4 import BeautifulSoup
import pandas as pd 
import numpy as np 
import requests

# Player Stats (Long Method)

In [412]:
base_url = "https://www.pba.ph/stats"

In [413]:
reqs = requests.get(base_url, headers = {'User-Agent':'Mozilla/5.0 (X11; Linux)'})

In [414]:
soup = BeautifulSoup(reqs.content, 'lxml')

In [415]:
stats = []

In [416]:
table_tag = soup.find('table')

In [417]:
tr_tag = table_tag.find_all('tr')

In [418]:
for td in tr_tag: 
    td_tag = td.find_all('td')
    for i in td_tag:
        stats.append(i.get_text())

In [419]:
player_name = stats[::23]

In [420]:
#player_name

In [421]:
stats[:10]

['J. Perez', '', '11', '37.18', '8.36', '19.18', '44%', '1.64', '6.09', '27%']

In [422]:
GP = stats[2::23]

In [423]:
# columns
MIN = stats[3::23]
FGM = stats[4::23]
FGA = stats[5::23]
FG_PER = stats[6::23] # FG%
THREE_PM = stats[7::23] # 3Pm
THREE_PA = stats[8::23] # 3Pa
THREE_P = stats[9::23] #3 P%
FTm = stats[10::23]
FTa = stats[11::23]
FT = stats[12::23] # FT%
APG = stats[13::23]
STL = stats[14::23]
BLK = stats[15::23]
oREB = stats[16::23]
dREB = stats[17::23]
REB = stats[18::23]
PF = stats[19::23]
TOV = stats[20::23]
PM = stats[21::23] # +/-
PTS = stats[22::23]

In [424]:
player_df = pd.DataFrame(player_name, columns = ['Player'])

In [425]:
player_df['MIN'] = MIN

In [426]:
player_df['FGM'] = FGM

In [427]:
player_df['FGA'] = FGA

In [428]:
player_df['FGA_PER'] = FG_PER

In [429]:
player_df['THREE_PM'] = THREE_PM

In [430]:
player_df['THREE_PA'] = THREE_PA

In [431]:
player_df['THREE_P'] = THREE_PA

In [432]:
player_df['FTm'] = FTm

In [433]:
player_df['FTa'] = FTa

In [434]:
player_df['FT'] = FT

In [435]:
player_df['APG'] = APG

In [436]:
player_df['STL'] = STL

In [437]:
player_df['BLK'] = BLK

In [438]:
player_df['oREB'] = oREB

In [439]:
player_df['dREB'] = dREB

In [440]:
player_df['REB'] = REB

In [441]:
player_df['PF'] = PF

In [442]:
player_df['TOV'] = TOV

In [443]:
player_df['PM'] = PM

In [444]:
player_df['PTS'] = PTS

In [445]:
player_df

,Player,MIN,FGM,FGA,FGA_PER,THREE_PM,THREE_PA,THREE_P,FTm,FTa,...,APG,STL,BLK,oREB,dREB,REB,PF,TOV,PM,PTS
0,J. Perez,37.18,8.36,19.18,44%,1.64,6.09,6.09,6.00,9.64,...,4.27,2.00,0.64,2.00,4.82,6.82,2.64,3.27,-7.45,24.36
1,M. Wright,40.92,7.64,17.09,45%,3.27,8.55,8.55,4.27,5.27,...,6.00,1.36,0.00,0.64,4.73,5.36,3.27,2.82,3.45,22.82
2,B. Parks,37.88,6.30,12.60,50%,3.00,6.50,6.50,4.50,5.30,...,2.60,1.20,0.40,1.90,6.30,8.20,2.80,2.30,5.40,20.10
3,P. Lee,30.28,6.27,13.36,47%,3.09,7.27,7.27,4.27,4.91,...,3.09,1.18,0.09,0.64,3.27,3.91,2.55,2.82,4.91,19.91
4,C. Standhardinger,37.49,8.00,16.20,49%,0.10,0.30,0.30,3.80,7.70,...,3.80,1.30,0.10,3.00,9.00,12.00,2.60,3.00,-8.50,19.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
228,A. Soberano,0.00,0.00,0.00,0%,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
229,R. Escoto,0.00,0.00,0.00,0%,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
230,R. Subido,0.00,0.00,0.00,0%,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
231,R. Publico,0.00,0.00,0.00,0%,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
232,K. Salado,0.00,0.00,0.00,0%,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

# Short Method

In [465]:
tab_tag_ = soup.find_all('table', {'id':'record-table'})

In [466]:
ps_df = pd.read_html(str(tab_tag_))

In [467]:
ps_df = pd.DataFrame(ps_df[0]).drop('Unnamed: 1', axis = 'columns')

In [468]:
ps_df

,PLAYERS,GP,MIN,FGm,FGa,FG%,3Pm,3Pa,3P%,FTm,...,APG,STL,BLK,oREB,dREB,REB,PF,TOV,+/-,PTS
0,J. Perez,11,37.18,8.36,19.18,44%,1.64,6.09,27%,6.00,...,4.27,2.00,0.64,2.00,4.82,6.82,2.64,3.27,-7.45,24.36
1,M. Wright,11,40.92,7.64,17.09,45%,3.27,8.55,38%,4.27,...,6.00,1.36,0.00,0.64,4.73,5.36,3.27,2.82,3.45,22.82
2,B. Parks,10,37.88,6.30,12.60,50%,3.00,6.50,46%,4.50,...,2.60,1.20,0.40,1.90,6.30,8.20,2.80,2.30,5.40,20.10
3,P. Lee,11,30.28,6.27,13.36,47%,3.09,7.27,43%,4.27,...,3.09,1.18,0.09,0.64,3.27,3.91,2.55,2.82,4.91,19.91
4,C. Standhardinger,10,37.49,8.00,16.20,49%,0.10,0.30,33%,3.80,...,3.80,1.30,0.10,3.00,9.00,12.00,2.60,3.00,-8.50,19.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
228,A. Soberano,0,0.00,0.00,0.00,0%,0.00,0.00,0%,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
229,R. Escoto,0,0.00,0.00,0.00,0%,0.00,0.00,0%,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
230,R. Subido,0,0.00,0.00,0.00,0%,0.00,0.00,0%,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
231,R. Publico,0,0.00,0.00,0.00,0%,0.00,0.00,0%,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
232,K. Salado,0,0.00,0.00,0.00,0%,0.00,0.00,0%,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

# Team Stats (Short Method)

In [449]:
team_url = "https://www.pba.ph/teamstats?conf=27356&type=AVG&stat=sWins&sort=DESC"

In [450]:
src = requests.get(team_url, headers = {'User-Agent':'Mozilla/5.0 (X11; Linux)'})

In [451]:
soup_ = BeautifulSoup(src.content, 'lxml')

In [452]:
team_stats = []

In [453]:
tab_tag = soup_.find('table', {'class':'teamstats-table'})

In [454]:
tab_df = pd.read_html(str(tab_tag))

In [455]:
tab_df = pd.DataFrame(tab_df[0])

In [456]:
tab_df 
# there's NaN because of the LOGO

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,OFFENSE STATS,OFFENSE STATS,OFFENSE STATS,OFFENSE STATS,OFFENSE STATS,OFFENSE STATS,OFFENSE STATS,OFFENSE STATS,OFFENSE STATS,OFFENSE STATS,...,OFFENSE STATS,OFFENSE STATS,OFFENSE STATS,OFFENSE STATS,OFFENSE STATS,OFFENSE STATS,OFFENSE STATS,OFFENSE STATS,OFFENSE STATS,OFFENSE STATS
1,NaN,GAME,GAME,3PT FGs,3PT FGs,3PT FGs,2PT FGs,2PT FGs,2PT FGs,FGs,...,MISC,MISC,TURNOVERS,TURNOVERS,FOULS,FASTBREAK,FASTBREAK,FASTBREAK,SCORING,SCORING
2,Teams,W-L,GP,M,A,%,M,A,%,M,...,STL,BLK,TO,PTS,FOULS,M,A,PTS,Bench,PTS
3,NaN,15 - 6,21,8.90,25.95,34%,24.76,49.57,50%,33.67,...,4.86,3.14,16.24,12.95,17.33,4.57,4.90,8.19,28.67,89.86
4,NaN,12 - 9,21,12.10,39.29,31%,22.38,44.19,51%,34.48,...,9.38,3.43,16.33,19.10,26.19,5.33,5.71,9.90,30.43,96.62
5,NaN,11 - 6,17,13.35,38.12,35%,20.71,43.29,48%,34.06,...,6.82,4.00,17.35,17.94,27.06,5.59,6.41,9.88,37.88,98.29
6,NaN,11 - 7,18,7.72,24.33,32%,25.56,53.94,47%,33.28,...,5.22,3.06,13.56,15.72,23.06,4.17,4.72,8.06,37.94,88.39
7,NaN,7 - 6,13,10.08,31.38,32%,22.77,47.69,48%,32.85,...,7.62,3.38,15.31,16.69,21.92,5.31,6.00,9.69,25.77,90.31
8,NaN,7 - 5,12,7.00,19.92,35%,28.92,59.75,48%,35.92,...,6.83,2.33,17.00,17.67,24.25,6.00,6.58,10.42,42.58,96.00
9,NaN,7 - 5,12,7.50,21.17,35%,26.25,56.58,46%,33.75,...,8.75,2.00,16.42,21.00,25.42,5.67,6.33,10.17,45.25,91.08
10,NaN,6 - 6,12,8.58,35.83,24%,18.92,42.42,45%,27.50,...,7.17,4.58,13.00,16.08,22.58,3.67,4.00,6.17,38.42,79.83
11,NaN,5 - 6,11,10.91,32.64,33%,27.64,52.45,53%,38.55,...,5.18,1.73,15.18,15.55,25.36,6.00,6.82,11.18,52.09,105.18
12,NaN,2 - 9,11,10.45,35.73,29%,20.55,47.27,43%,31.00,...,6.18,2.91,15.55,17.09,26.18,5.27,6.00,9.18,46.09,90.09
13,NaN,1 - 10,11,10.27,31.36,33%,23.00,48.82,47%,33.27,...,6.36,3.00,14.09,17.36,23.91,9.00,10.00,14.91,43.36,94.55
14,NaN,1 - 10,11,10.45,32.55,32%,20.73,45.82,45%,31.18,...,5.45,1.73,15.91,15.18,23.64,4.64,5.18,8.36,34.45,89.64